<?php
use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function signalwire_help($route_name, RouteMatchInterface $route_match) {
    switch ($route_name) {
        // Main module help for the signalwire module.
        case 'help.page.signalwire':
            $output = '';
            $output .= '<h3>' . t('About') . '</h3>';
            $output .= '<p>' . t('Integrates Drupal 8 to Signalwire.') . '</p>';
            return $output;

        default:
    }
}